

# TURTLE: BIBLIOTECA DE CRIAR ANIMAÇOES

# MATPLOTLIB: BIBLIOTECA PARA CIRAÇÃO DE GRÁFICOS

# PILLOW: USADA PARA MANIPULAR IMAGENS

# SEABORN: USADA PARA GRÁFICOS ESTATISTICOS INSPEÇÃO

# OPENCV: USADA PARA PROCESSAR IMAGENS E VISÃO COMPUTACIONAL

# PLOTLY: BIBLIOTECA PARA GRÁFICOS COM INERATIVIDADE "MENU"